// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: example.proto

package chat_package

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Example_UnaryCall_FullMethodName                  = "/chat_package.Example/unaryCall"
	Example_ServerStreamingCall_FullMethodName        = "/chat_package.Example/serverStreamingCall"
	Example_ClientStreamingCall_FullMethodName        = "/chat_package.Example/clientStreamingCall"
	Example_BidirectionalStreamingCall_FullMethodName = "/chat_package.Example/bidirectionalStreamingCall"
)

// ExampleClient is the client API for Example service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExampleClient interface {
	UnaryCall(ctx context.Context, in *ClientMessage, opts ...grpc.CallOption) (*ServerMessage, error)
	ServerStreamingCall(ctx context.Context, in *ClientMessage, opts ...grpc.CallOption) (Example_ServerStreamingCallClient, error)
	ClientStreamingCall(ctx context.Context, opts ...grpc.CallOption) (Example_ClientStreamingCallClient, error)
	BidirectionalStreamingCall(ctx context.Context, opts ...grpc.CallOption) (Example_BidirectionalStreamingCallClient, error)
}

type exampleClient struct {
	cc grpc.ClientConnInterface
}

func NewExampleClient(cc grpc.ClientConnInterface) ExampleClient {
	return &exampleClient{cc}
}

func (c *exampleClient) UnaryCall(ctx context.Context, in *ClientMessage, opts ...grpc.CallOption) (*ServerMessage, error) {
	out := new(ServerMessage)
	err := c.cc.Invoke(ctx, Example_UnaryCall_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) ServerStreamingCall(ctx context.Context, in *ClientMessage, opts ...grpc.CallOption) (Example_ServerStreamingCallClient, error) {
	stream, err := c.cc.NewStream(ctx, &Example_ServiceDesc.Streams[0], Example_ServerStreamingCall_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &exampleServerStreamingCallClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Example_ServerStreamingCallClient interface {
	Recv() (*ServerMessage, error)
	grpc.ClientStream
}

type exampleServerStreamingCallClient struct {
	grpc.ClientStream
}

func (x *exampleServerStreamingCallClient) Recv() (*ServerMessage, error) {
	m := new(ServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exampleClient) ClientStreamingCall(ctx context.Context, opts ...grpc.CallOption) (Example_ClientStreamingCallClient, error) {
	stream, err := c.cc.NewStream(ctx, &Example_ServiceDesc.Streams[1], Example_ClientStreamingCall_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &exampleClientStreamingCallClient{stream}
	return x, nil
}

type Example_ClientStreamingCallClient interface {
	Send(*ClientMessage) error
	CloseAndRecv() (*ServerMessage, error)
	grpc.ClientStream
}

type exampleClientStreamingCallClient struct {
	grpc.ClientStream
}

func (x *exampleClientStreamingCallClient) Send(m *ClientMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *exampleClientStreamingCallClient) CloseAndRecv() (*ServerMessage, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exampleClient) BidirectionalStreamingCall(ctx context.Context, opts ...grpc.CallOption) (Example_BidirectionalStreamingCallClient, error) {
	stream, err := c.cc.NewStream(ctx, &Example_ServiceDesc.Streams[2], Example_BidirectionalStreamingCall_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &exampleBidirectionalStreamingCallClient{stream}
	return x, nil
}

type Example_BidirectionalStreamingCallClient interface {
	Send(*ClientMessage) error
	Recv() (*ServerMessage, error)
	grpc.ClientStream
}

type exampleBidirectionalStreamingCallClient struct {
	grpc.ClientStream
}

func (x *exampleBidirectionalStreamingCallClient) Send(m *ClientMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *exampleBidirectionalStreamingCallClient) Recv() (*ServerMessage, error) {
	m := new(ServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExampleServer is the server API for Example service.
// All implementations must embed UnimplementedExampleServer
// for forward compatibility
type ExampleServer interface {
	UnaryCall(context.Context, *ClientMessage) (*ServerMessage, error)
	ServerStreamingCall(*ClientMessage, Example_ServerStreamingCallServer) error
	ClientStreamingCall(Example_ClientStreamingCallServer) error
	BidirectionalStreamingCall(Example_BidirectionalStreamingCallServer) error
	mustEmbedUnimplementedExampleServer()
}

// UnimplementedExampleServer must be embedded to have forward compatible implementations.
type UnimplementedExampleServer struct {
}

func (UnimplementedExampleServer) UnaryCall(context.Context, *ClientMessage) (*ServerMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryCall not implemented")
}
func (UnimplementedExampleServer) ServerStreamingCall(*ClientMessage, Example_ServerStreamingCallServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreamingCall not implemented")
}
func (UnimplementedExampleServer) ClientStreamingCall(Example_ClientStreamingCallServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreamingCall not implemented")
}
func (UnimplementedExampleServer) BidirectionalStreamingCall(Example_BidirectionalStreamingCallServer) error {
	return status.Errorf(codes.Unimplemented, "method BidirectionalStreamingCall not implemented")
}
func (UnimplementedExampleServer) mustEmbedUnimplementedExampleServer() {}

// UnsafeExampleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExampleServer will
// result in compilation errors.
type UnsafeExampleServer interface {
	mustEmbedUnimplementedExampleServer()
}

func RegisterExampleServer(s grpc.ServiceRegistrar, srv ExampleServer) {
	s.RegisterService(&Example_ServiceDesc, srv)
}

func _Example_UnaryCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).UnaryCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Example_UnaryCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).UnaryCall(ctx, req.(*ClientMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_ServerStreamingCall_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExampleServer).ServerStreamingCall(m, &exampleServerStreamingCallServer{stream})
}

type Example_ServerStreamingCallServer interface {
	Send(*ServerMessage) error
	grpc.ServerStream
}

type exampleServerStreamingCallServer struct {
	grpc.ServerStream
}

func (x *exampleServerStreamingCallServer) Send(m *ServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _Example_ClientStreamingCall_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExampleServer).ClientStreamingCall(&exampleClientStreamingCallServer{stream})
}

type Example_ClientStreamingCallServer interface {
	SendAndClose(*ServerMessage) error
	Recv() (*ClientMessage, error)
	grpc.ServerStream
}

type exampleClientStreamingCallServer struct {
	grpc.ServerStream
}

func (x *exampleClientStreamingCallServer) SendAndClose(m *ServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *exampleClientStreamingCallServer) Recv() (*ClientMessage, error) {
	m := new(ClientMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Example_BidirectionalStreamingCall_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExampleServer).BidirectionalStreamingCall(&exampleBidirectionalStreamingCallServer{stream})
}

type Example_BidirectionalStreamingCallServer interface {
	Send(*ServerMessage) error
	Recv() (*ClientMessage, error)
	grpc.ServerStream
}

type exampleBidirectionalStreamingCallServer struct {
	grpc.ServerStream
}

func (x *exampleBidirectionalStreamingCallServer) Send(m *ServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *exampleBidirectionalStreamingCallServer) Recv() (*ClientMessage, error) {
	m := new(ClientMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Example_ServiceDesc is the grpc.ServiceDesc for Example service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Example_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat_package.Example",
	HandlerType: (*ExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "unaryCall",
			Handler:    _Example_UnaryCall_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "serverStreamingCall",
			Handler:       _Example_ServerStreamingCall_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "clientStreamingCall",
			Handler:       _Example_ClientStreamingCall_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "bidirectionalStreamingCall",
			Handler:       _Example_BidirectionalStreamingCall_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "example.proto",
}
